version: '3.3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ihsan
      POSTGRES_PASSWORD: ihsan
      POSTGRES_DB: social
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local